### ISSUE TITLE
请尝试更改或去除进入视频详情页头部的视频封面

### ISSUE THREAD

**Issue by kidnappe** [SpaceXC/WearBili#10]
按照手机的使用逻辑，那张封面很容易让人以为是视频播放的窗口，但实际上在手表上点击只能让人看到放大的视频封面，并且实测在ow2上无法返回。
我建议：是否尝试将播放按钮放在原先放置视频封面的位置，或者删除。否则极易产生误导。_（并且作者竟然十分贴心的增加了视频时间，大大增加了误触的风险）_
软件版本1.0.1

**Comment by SpaceXC** [comment]
这玩意就是之前有人说点击封面播放视频太反人类才改掉的。。。

**Comment by kidnappe** [comment]
要这个看封面的功能有啥用呢？不如作者统计一下看看哪个方案喜欢的人多，就用哪个。我觉得还是现在这个更反人类一点



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月31日(周二) 中午12:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SpaceXC/WearBili] 请尝试更改或去除进入视频详情页头部的视频封面 (Issue #10)




 
这玩意就是之前有人说点击封面播放视频太反人类才改掉的。。。

**Comment by SpaceXC** [comment]
首先，这个查看封面你可以不用，但我觉得不能没有
其次，查看封面大图这里，可以长按屏幕返回
然后，下面播放按钮：？？？
