### ISSUE TITLE
闪退加剧（重大bug）

### ISSUE THREAD

**Issue by minecraftHCX** [SpaceXC/WearBili#22]
似乎是因为b站的部分改动，闪退现象加剧：
1.绝大部分视频加载时均有闪退现象
2.进入关于页时闪退
3.点击播放时使用内置播放器极高概率闪退（音频播放器卡死，可能有关）
4.进入up主个人主页时闪退
总结：严重影响使用！
注：以上情况在所有内测版均出现，初步推测是b站数据传输的调整引起（隔壁腕上哔哩个人主页无法查看，可能是相同情况），希望尽快解决_(:з」∠)_。
其他：按钮失效（长按的缓存键，我的信息键失效）

**Comment by chhongzh** [comment]
同样，日志Gson报错。接口返回内容异常，无法解析（

**Comment by minecraftHCX** [comment]
> 

对，软件没有处理返回的异常，直接崩溃闪退
