### ISSUE TITLE
dex过大

### ISSUE THREAD

**Issue by qiunanrima** [SpaceXC/WearBili#6]
dex太大了，对小内存设备极不友好，希望能精简一下代码

**Comment by SpaceXC** [comment]
你都看到dex了，为什么没看到这个







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SpaceXC/WearBili"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月27日(星期五) 中午12:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[SpaceXC/WearBili] dex过大 (Issue #6)





 
dex太大了，对小内存设备极不友好，希望能精简一下代码

**Comment by SpaceXC** [comment]
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/60663465/215014973-068a72f8-d859-4e5c-8851-b051dde144a7.png">
你都知道有dex这种东西了，为什么看不见这个（

**Comment by pai233** [comment]
> <img alt="image" width="1336" src="https://user-images.githubusercontent.com/60663465/215014973-068a72f8-d859-4e5c-8851-b051dde144a7.png">
> 
> 你都知道有dex这种东西了，为什么看不见这个（

正确的
